### ISSUE TITLE
Remove 'regenerate thumbnails' from the assets tab.

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-clipped-extension#14]
This will probably cause lots of issues if the average user just clicks it. Let's remove this button.

**Comment by danigirl329** [comment]
I believe this has been resolved already, maybe not documented. 

only_allow_access_to :regenerate,
    :when => [:admin],
    :denied_url => { :controller => 'admin/assets', :action => 'index' },
    :denied_message => 'You must have admin privileges to refresh the whole asset set.'
