### ISSUE TITLE
Updloading asset file with no extension breaks trusty

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-clipped-extension#17]
1) Create a file, like alt_12345 (no extension)
2) upload and attach to a page
3) Try editing the page

Here is the error:
Error detected in: CD.org Test (production)
Full report at https://app.honeybadger.io/projects/46605/faults/26256797
ActionView::Template::Error: undefined method `image?' for nil:NilClass
________________________________________
Summary
admin/pages#edit
https://test.culturaldistrict.org:9443/admin/pages/8434/edit?return_to=https%3A%2F%2Ftest.culturaldistrict.org%3A9443%2Fadmin%2Fproductions
Trace
gems/trusty-clipped-extension-2.0.5/app/views/admin/page_attachments/_attachment.html.haml:5:in `__var_lib_gems_______gems_trusty_clipped_extension_______app_views_admin_page_attachments__attachment_html_haml__3397937116080857596_70212540182740`
gems/actionview-4.2.5.1/lib/action_view/template.rb:145:in `block in render`
gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument`

**Comment by Brit200313** [comment]
Resolved here: https://github.com/pgharts/trusty-clipped-extension/pull/22

Thanks for reporting!
